=== shiv6198/XML-Programming/bookstore.dtd
<!ELEMENT person (name, age, address, phone, email)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT address (street, city, state, zip)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT zip (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT email (#PCDATA)>

=== shiv6198/XML-Programming/bookstore.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE person SYSTEM "bookstore.dtd">
    <person>
      <name>John Doe</name>
      <age>25</age>
      <address>
        <street>123 Main Street</street>
        <city>New York</city>
        <state>NY</state>
        <zip>12345</zip>
      </address>
      <phone >555-555-5555</phone>
      <email>john@example.com</email>
    </person>
